import re

filepath = r'C:\PERSONAL\gachngoigachngoi\FE\src\pages\Home\Home.tsx'

# Read file
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Common replacements
replacements = {
    'Ng𝑜𝑖': 'Ngói',
    'ng𝑜𝑖': 'ngói',
    '𝑎𝑚': 'âm',
    'd𝑢𝑜𝑛𝑔': 'dương',
    'Lo𝑎𝑖': 'Loại',
    'truy𝑒̀𝑛': 'truyền',
    'th𝑜̂́𝑛𝑔': 'thống',
    'thi𝑒́𝑡': 'thiết',
    'k𝑒́': 'kế',
    '𝑑𝑜𝑐̀': 'độc',
    '𝑑𝑎𝑜': 'đáo',
    't𝑎𝑜': 'tạo',
    'n𝑒̂𝑛': 'nên',
    'm𝑎́𝑖': 'mái',
    'nh𝑎̀': 'nhà',
    'b𝑒̀𝑛': 'bền',
    'v𝑢̛𝑛𝑔': 'vững',
    'm𝑢̃𝑖': 'mũi',
    'h𝑎̀𝑖': 'hài',
    'cong': 'cong',
    'm𝑜́𝑖': 'mới',
    'th𝑢𝑜𝑛𝑔': 'thường',
    'd𝑢̀𝑛𝑔': 'dùng',
    '𝑑𝑖𝑛𝑕': 'đình',
    'ch𝑢̀𝑎': 'chùa',
    'c𝑜̂': 'cổ',
    'G𝑎𝑐𝑕': 'Gạch',
    'l𝑎́𝑡': 'lát',
    's𝑎̀𝑛': 'sàn',
    'v𝑢̛𝑛𝑔': 'vững',
    '𝑑𝑒̉𝑝': 'đẹp',
    'qua': 'qua',
    'th𝑜̛𝑖': 'thời',
    'gian': 'gian',
    'x𝑎̂𝑦': 'xây',
    'd𝑢̛𝑛𝑔': 'dựng',
    'theo': 'theo',
    'phong': 'phong',
    'c𝑎́𝑐𝑕': 'cách',
    'ch𝑎́𝑐': 'chắc',
    'kh𝑜̉𝑒': 'khỏe',
    'trang': 'trang',
    'tr𝑖́': 'trí',
    'hoa': 'hoa',
    'v𝑎̆𝑛': 'văn',
    '𝑑𝑜𝑐̀': 'độc',
    'nh𝑎̃𝑛': 'nhãn',
    'c𝑜̂𝑛𝑔': 'công',
    'tr𝑖̀𝑛𝑕': 'trình',
    'Ch𝑜𝑛': 'Chọn',
    '𝑑𝑎́𝑡': 'đất',
    'L𝑢̛𝑎': 'Lựa',
    'ch𝑜𝑛': 'chọn',
    's𝑒́𝑡': 'sét',
    'ch𝑎́𝑡': 'chất',
    'l𝑢𝑜𝑛𝑔': 'lượng',
    't𝑢̀': 'từ',
    'v𝑢̀𝑛𝑔': 'vùng',
    'nguy𝑒̂𝑛': 'nguyên',
    'li𝑒̆𝑢': 'liệu',
    'Nh𝑎̀𝑜': 'Nhào',
    'tr𝑜𝑛': 'trộn',
    'v𝑜́𝑖': 'với',
    'n𝑢𝑜́𝑐': 'nước',
    't𝑦̉': 'tỷ',
    'l𝑒̣': 'lệ',
    'chu𝑎̉𝑛': 'chuẩn',
    'c𝑢𝑎': 'của',
    'l𝑎̀𝑛𝑔': 'làng',
    'ngh𝑒̀': 'nghề',
    'T𝑎𝑜': 'Tạo',
    'h𝑖̀𝑛𝑕': 'hình',
    'Ngh𝑒̀': 'Nghệ',
    'nh𝑎̂𝑛': 'nhân',
    'th𝑢̉': 'thủ',
    't𝑢̛𝑛𝑔': 'từng',
    'vi𝑒̂𝑛': 'viên',
    'Ph𝑜̆𝑖': 'Phơi',
    'kh𝑜̂': 'khô',
    's𝑎̉𝑛': 'sản',
    'ph𝑎̉𝑚': 'phẩm',
    'd𝑢̛𝑜́𝑖': 'dưới',
    '𝑎́𝑛𝑕': 'ánh',
    'n𝑎́𝑛𝑔': 'nắng',
    't𝑢̛': 'tự',
    'nhi𝑒̂𝑛': 'nhiên',
    'trong': 'trong',
    'nhi𝑒̀𝑢': 'nhiều',
    'ng𝑎̀𝑦': 'ngày',
    'Nung': 'Nung',
    'l𝑜̀': 'lò',
    '𝑜̀': 'ở',
    'nhi𝑒̣𝑡': 'nhiệt',
    '𝑑𝑜̂': 'độ',
    '𝑑𝑢𝑜𝑛𝑔': 'đường',
    'L𝑎̀𝑚': 'Làm',
    'An': 'An',
    'Ch𝑢̀𝑎': 'Chùa',
    'B𝑎́𝑖': 'Bái',
    '𝐷𝑖̀𝑛𝑕': 'Đính',
}

# Apply replacements
for old, new in replacements.items():
    content = content.replace(old, new)

# Write back
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("✅ Fixed Home.tsx")
