const path = {
  home: '/',
  products: '/san-pham',
  productCategory: '/san-pham/:category',
  productDetail: '/san-pham/:category/:id',
  projects: '/du-an',
  projectDetail: '/du-an/:slug',
  blog: '/blog',
  blogPost: '/blog/:slug',
  about: '/gioi-thieu',
  contact: '/lien-he',
  user: '/user',
  profile: '/user/profile',
  changePassword: '/user/password',
  historyPurchase: '/user/purchase',
  login: '/login',
  register: '/register',
  logout: '/logout',
  cart: '/cart',
  // Admin routes
  admin: '/admin',
  adminDashboard: '/admin/dashboard',
  adminProducts: '/admin/products',
  adminCategories: '/admin/categories',
  adminOrders: '/admin/orders',
  adminOrderNew: '/admin/orders/new',
  adminOrderEdit: '/admin/orders/:id/edit',
  adminCustomers: '/admin/customers',
  adminUsers: '/admin/users',
  adminPosts: '/admin/posts',
  adminPostNew: '/admin/posts/new',
  adminPostEdit: '/admin/posts/:id/edit',
  adminAnalytics: '/admin/analytics',
  adminSettings: '/admin/settings',
  // Error pages
  unauthorized: '/403',
  notFound: '/404'
} as const

export default path
